# Generated by Django 3.1.7 on 2021-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ticker', models.CharField(max_length=5, unique=True)),
                ('latest_sentiment_score', models.FloatField(max_length=4)),
                ('latest_stock_price', models.FloatField()),
                ('daily_sentiment_trend', models.FloatField()),
                ('daily_stock_trend', models.FloatField()),
            ],
        ),
    ]
